### ISSUE TITLE
BFF 2.8 Failing due to some errors

### ISSUE THREAD

**Issue by s0h3ck** [CERTCC/certfuzz#15]
Hi,

I run BFF 2.8, bff.py from the command line in a Windows 10 VM (x64) with at least 8192 MB of memory and I have at least 5.81 GB of hard drive space. I run the program in administrator permission and after fuzzing a project, I got the following error:

```text
2017-04-05 13:54:52,088 WARNING certfuzz.iteration.iteration_windows - WindowsIteration terminating abnormally due to AttributeError: winmgmts:.Win32_PerfRawData_PerfProc_Process
Traceback (most recent call last):
  File "C:\BFF\bff.py", line 51, in <module>
    main()
  File "C:\BFF\certfuzz\bff\windows.py", line 62, in main
    bff()
  File "C:\BFF\certfuzz\bff\common.py", line 169, in go
    campaign.go()
  File "C:\BFF\certfuzz\campaign\campaign_base.py", line 577, in go
    self._do_interval()
  File "C:\BFF\certfuzz\campaign\campaign_base.py", line 552, in _do_interval
    self._do_iteration(sf, r, seednum)
  File "C:\BFF\certfuzz\campaign\campaign_windows.py", line 213, in _do_iteration
    iteration()
  File "C:\BFF\certfuzz\iteration\iteration_base.py", line 296, in go
    self.construct_testcase()
  File "C:\BFF\certfuzz\iteration\iteration_base.py", line 235, in construct_testcase
    self._construct_testcase()
  File "C:\BFF\certfuzz\iteration\iteration_windows.py", line 155, in _construct_testcase
    copy_fuzzedfile=self.fuzzer.fuzzed_changes_input) as testcase:
  File "C:\BFF\certfuzz\testcase\testcase_base.py", line 117, in __enter__
    self.update_crash_details()
  File "C:\BFF\certfuzz\testcase\testcase_windows.py", line 152, in update_crash_details
    self.debug()
  File "C:\BFF\certfuzz\testcase\testcase_windows.py", line 220, in debug
    self.debug_once()
  File "C:\BFF\certfuzz\testcase\testcase_windows.py", line 164, in debug_once
    self.parsed_outputs.append(debugger.go())
  File "C:\BFF\certfuzz\debuggers\msec.py", line 212, in go
    self.run_with_timer()
  File "C:\BFF\certfuzz\debuggers\msec.py", line 177, in run_with_timer
    for proc in self.wmiInterface.Win32_PerfRawData_PerfProc_Process(IDProcess=child_pid):
  File "C:\Python27\lib\site-packages\wmi.py", line 1147, in __getattr__
    return getattr (self._namespace, attribute)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: winmgmts:.Win32_PerfRawData_PerfProc_Process
```

The version of python I use is 2.7.12. The BFF 2.8 configuration use the default configuration (bytemut fuzzer), except that I removed the NUL option in the cmdline_template in bff.yaml.

The issue is not consistent and sometimes I can get an error only after two minutes, but sometimes it can run for a about day without complaining. Here is an example of a MemoryError I got recently:

```text
  File "C:\BFF\bff.py", line 51, in <module>
    main()
  File "C:\BFF\certfuzz\bff\windows.py", line 62, in main
    bff()
  File "C:\BFF\certfuzz\bff\common.py", line 169, in go
    campaign.go()
  File "C:\BFF\certfuzz\campaign\campaign_base.py", line 577, in go
    self._do_interval()
  File "C:\BFF\certfuzz\campaign\campaign_base.py", line 552, in _do_interval
    self._do_iteration(sf, r, seednum)
  File "C:\BFF\certfuzz\campaign\campaign_windows.py", line 213, in _do_iteration
    iteration()
  File "C:\BFF\certfuzz\iteration\iteration_base.py", line 297, in go
    self.process_testcases()
  File "C:\BFF\certfuzz\iteration\iteration_base.py", line 288, in process_testcases
    pipeline.go()
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 339, in go
    self.analysis_pipeline.send(testcase)
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 161, in verify
    target.send(testcase)
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 171, in minimize
    self._minimize(testcase)	
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 267, in _minimize
    m.go()
  File "C:\BFF\certfuzz\minimizer\minimizer_base.py", line 734, in go
    self.swap_bytes()
  File "C:\BFF\certfuzz\minimizer\minimizer_base.py", line 892, in swap_bytes
    self.seed, self.fuzzed_content)
  File "C:\BFF\certfuzz\minimizer\minimizer_base.py", line 918, in bytewise_swap2
    append(a)
MemoryError
```

Any ideas to solve these issues?

**Comment by wdormann** [comment]
Hi s0h3ck,

Regarding the first issue, I've never seen that error before.  Are you running BFF as a different user than the logged-in user?   If so, I'd suggest avoiding that.   As a workaround, you can set the "watchcpu" option to "False" in bff.yaml.

Regarding the second issue, I've occasionally seen that as well.  Minimization can take a lot of memory.  And the Python dependencies that BFF uses don't seem to all have 64-bit downloads available, so 64-bit python doesn't seem to be practical.   As a workaround here, you can disable minimization in bff.yaml.

**Comment by wdormann** [comment]
And just as a follow-up, it **is** possible to use BFF with the 64-bit version of python.  You just need to download and install the 64-bit versions of the dependencies outlined in the readme.  Some, like scipy and numpy are available in whl format, which requires PIP to be installed for Python 2.7.

**Comment by s0h3ck** [comment]
Hi wdormann,

I reinstalled BFF 2.8 with the 64-bit version of python with those dependencies:

yaml - PyYAML-3.12.win-amd64-py2.7.exe
wmi - PyMI-1.0.4-cp27-none-win_amd64.whl
six - six-1.10.0-py2.py3-none-any.whl
numpy - numpy‑1.12.1+mkl‑cp34‑cp34m‑win_amd64.whl

So far, I didn't have a new crash with BFF 2.8, but as I mentioned earlier it didn't happen to me often, so I will keep you updated if there is something new. Thanks.

**Comment by 0xD34DC0DE** [comment]
Hi Im getting the same issues as s0h3ck had

**Comment by wdormann** [comment]
You could try installing the 64-bit python and dependencies as a workaround.
