### ISSUE TITLE
Contact fuzzer crash

### ISSUE THREAD

**Issue by neox123** [CERTCC/certfuzz#22]
Hello.

If run the fuzzer for more than 3 days, an error occurs on the way.

It is as follows.

What is the solution?

Thanks.

crash log:
```
2018-11-22 06:02:11,719 INFO certfuzz.minimizer.minimizer_base - testcase=0x5133
7628.0x71717171.0x77aa2f50 signal=None
2018-11-22 06:03:18,996 WARNING certfuzz.iteration.iteration_windows - WindowsIt
eration terminating abnormally due to error: can't start new thread
Traceback (most recent call last):
  File "C:\BFF\bff.py", line 51, in <module>
    main()
  File "C:\BFF\certfuzz\bff\windows.py", line 62, in main
    bff()
  File "C:\BFF\certfuzz\bff\common.py", line 169, in go
    campaign.go()
  File "C:\BFF\certfuzz\campaign\campaign_base.py", line 577, in go
    self._do_interval()
  File "C:\BFF\certfuzz\campaign\campaign_base.py", line 552, in _do_interval
    self._do_iteration(sf, r, seednum)
  File "C:\BFF\certfuzz\campaign\campaign_windows.py", line 213, in _do_iteratio
n
    iteration()
  File "C:\BFF\certfuzz\iteration\iteration_base.py", line 297, in go
    self.process_testcases()
  File "C:\BFF\certfuzz\iteration\iteration_base.py", line 288, in process_testc
ases
    pipeline.go()
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 339, in go
    self.analysis_pipeline.send(testcase)
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 161, in verify
    target.send(testcase)
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 171, in minimize
    self._minimize(testcase)
  File "C:\BFF\certfuzz\tc_pipeline\tc_pipeline_base.py", line 267, in _minimize

    m.go()
  File "C:\BFF\certfuzz\minimizer\minimizer_base.py", line 798, in go
    if self.is_same_crash():
  File "C:\BFF\certfuzz\minimizer\minimizer_base.py", line 586, in is_same_crash

    newcrash = self._crash_builder()
  File "C:\BFF\certfuzz\minimizer\minimizer_base.py", line 517, in _crash_builde
r
    new_testcase.update_crash_details()
  File "C:\BFF\certfuzz\testcase\testcase_windows.py", line 152, in update_crash
_details
    self.debug()
  File "C:\BFF\certfuzz\testcase\testcase_windows.py", line 228, in debug
    self.debug_once()
  File "C:\BFF\certfuzz\testcase\testcase_windows.py", line 164, in debug_once
    self.parsed_outputs.append(debugger.go())
  File "C:\BFF\certfuzz\debuggers\msec.py", line 212, in go
    self.run_with_timer()
  File "C:\BFF\certfuzz\debuggers\msec.py", line 172, in run_with_timer
    self.t.start()
  File "C:\Python27\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

**Comment by wdormann** [comment]
If python can't start a thread, that sounds like a Windows problem, as opposed to a BFF bug.  Ensure that you have enough RAM in the fuzzing VM.
