### ISSUE TITLE
Error after install the FOE2

### ISSUE THREAD

**Issue by wyylucky** [CERTCC/certfuzz#9]
hello friends,
    After I installed the FOE2.1, I finished and run the foe2. But I get the error as follows.
    I read the readme.txt and change a software still get the same error. Now I know little about the implement, hope to give me some advice about how to deal with the error.
    (I have tried to install it on xp-32bit and xp-64bit)

2016-10-21 09:29:00,042 INFO certfuzz.file_handlers.seedfile_set - Adding file t
o set: C:\FOE2\fuzzdir\campaign_rcjfiz\seedfiles\sf_fcd1633dfbd46b7429060fa918ee
38ef.eps
Traceback (most recent call last):
  File "C:\FOE2\foe2.py", line 171, in <module>
    main()
  File "C:\FOE2\foe2.py", line 164, in main
    with WindowsCampaign(config_file=options.configfile, result_dir=options.resu
ltdir, debug=options.debug) as campaign:
  File "C:\FOE2\certfuzz\campaign\campaign.py", line 453, in **enter**
    self._cache_app()
  File "C:\FOE2\certfuzz\campaign\campaign.py", line 465, in _cache_app
    p = Popen(self.prog, cwd=targetdir)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
TypeError: _execute_child() takes exactly 17 arguments (18 given)

**Comment by wdormann** [comment]
This is fixed in BFF 2.8
https://www.cert.org/vulnerability-analysis/tools/bff-download.cfm
